apiVersion: v1
kind: Pod
metadata:
  name: greenops-test-pod
  labels:
    app: greenops-test
spec:
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.6
  nodeSelector:
    kubernetes.io/hostname: k8s-worker2
